Configuring category list item
megabitid/LostnFound_Android pull request #2
Opened 2020-11-10 08:19 UTC by MtaufiqH

build category list item

2020-11-10 19:05 UTC, DhytoDev commented
- Tolong lampirkan screenshoot (versi figma dan aktual)
- Tolong tambahkan saya atau Andi sebagai reviewer

2020-11-10 19:08 UTC, DhytoDev requested changes

2020-11-10 19:08 UTC, DhytoDev commented on app/src/main/java/id/taufiq/lostandfound/HomeActivity.kt
> +        rv_category.adapter = CategoryAdapter(this,data){
ini masih menampilkan semua yang ada di list di'? Kalau mengacu ke figma harusnya cuma tampilkan tiga kan, selebihnya bisa dilihat dengan tekan lainnya.

2020-11-10 23:58 UTC, MtaufiqH commented on app/src/main/java/id/taufiq/lostandfound/HomeActivity.kt
> +        rv_category.adapter = CategoryAdapter(this,data){
iya kak, jadi code yang saya harus lakukan baiknya  diimplementasikan bagaimana kak? terima kasih.

2020-11-11 02:43 UTC, DhytoDev commented on app/src/main/java/id/taufiq/lostandfound/HomeActivity.kt
> +        rv_category.adapter = CategoryAdapter(this,data){
Seingatku, list di kotlin itu ada method subList gitu. 

`data.subList(0,2)` 
Gini klo nda salah, cobami eksplor. Ada banyak itu method untuk manipulasi List.

2020-11-11 03:25 UTC, MtaufiqH commented on app/src/main/java/id/taufiq/lostandfound/HomeActivity.kt
> +        rv_category.adapter = CategoryAdapter(this,data){
kalau di adapter getItemView diiubah menjadi 3/4 saja ?

2020-11-13 16:56 UTC, merged